spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:alura-forum
  h2:
    console:
      enabled: 'true'
      path: /h2-console
  application:
    name: Sistema de Vendas desenvolvimento
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: 'false'
        show_sql: 'false'
    defer-datasource-initialization: 'true'
    hibernate:
      ddl-auto: update
  sql:
    init:
      username: sa
      password: ''
